<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="2.284" timestamp="2025-01-22T12:26:02.860198" hostname="NB-XCV17E418446"><testcase classname="test" name="test_sum_two_numbers" time="0.003" /><testcase classname="test" name="test_sum_two_decimals" time="0.003"><properties><property name="testrail_attachment" value="sample_reports/testrail.jpg" /></properties><failure message="assert (0.8 + 0.3) == 1.2">record_property = &lt;function record_property.&lt;locals&gt;.append_property at 0x000001623514E840&gt;

    def test_sum_two_decimals(record_property):
        record_property("testrail_attachment", "sample_reports/testrail.jpg")
&gt;       assert 0.8 + 0.3 == 1.2
E       assert (0.8 + 0.3) == 1.2

test.py:23: AssertionError</failure></testcase><testcase classname="test" name="test_sum_multiple_numbers[3+5-8]" time="0.001" /><testcase classname="test" name="test_sum_multiple_numbers[2+4-6]" time="0.001" /></testsuite></testsuites>